---
#- name: install the docker clean cron
#  cron:
#    name: "docker clean"
#    job:  "docker ps -a -q -f 'status=exited' -f 'status=created' -f 'status=dead' |xargs docker rm"
#    backup: yes
#    state: absent
#    minute: 0
#    hour: "*"
#    month: "*"
#    weekday: "*"
#    day: "*"
#
#- name: install the docker image clean
#  cron:
#    name: "docker image clean"
#    job: "docker images -q -f 'dangling=true'|xargs docker rmi"
#    backup: yes
#    state: absent
#    minute: 0
#    hour: "*"
#    month: "*"
#    weekday: "*"
#    day: "*"
#
#- name: install the docker volume clean
#  cron:
#    name: "docker volume clean"
#    job: "docker volume ls -qf dangling=true | xargs -r docker volume rm"
#    backup: yes
#    state: absent
#    minute: 0
#    hour: "*"
#    month: "*"
#    weekday: "*"
#    day: "*"

- name: copy the clean up script to remote host
  copy:
    src: cleanup.sh
    dest: /usr/bin
    mode: 0755

- name: install the cleanup script
  cron:
    name: "docker clean script"
    job: "/usr/bin/cleanup.sh"
    backup: yes
    state: present
    minute: 0
    hour: "*"
    month: "*"
    weekday: "*"
    day: "*"
