---
mesos_ip: "{{ ipaddr }}"
mesos_hostname: "{{ ipaddr }}"
mesos_apt_package: "mesos=1.2.0-2.0.6"
mesos_containerizers: "docker,mesos"
mesos_install_mode: "master-slave"
mesos_quorum: 2
mesos_additional_configs:
  - name: LOG_LEVEL
    value: WARNING
mesos_master_additional_flags:
  - quiet
mesos_master_additional_configs:
  - name: LOGGING_LEVEL
    value: INFO
  - name: ROLES
    value: system
mesos_slave_additional_configs:
  - name: LOGGING_LEVEL
    value: INFO
  - name: RESOURCES
    value: '"cpus:0;mem:0;disk:0;ports:[];cpus(system):0.5;mem(system):2560;disk(system):10240;ports(system):[1-10000];"'
  - name: ATTRIBUTES
    value: '"role:consul-master;"'